name: Cache Final

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-a155bc5

      - name: prime-cache-a155bc5
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"
